const Data = [
  "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos, vitae deserunt debitis eos neque laudantium cumque excepturi veniam magnam, tenetur, nemo eum laborum. Qui repellat corrupti illo repudiandae ea, commodi consectetur dicta nemo molestias maxime amet optio similique dolorum temporibus.",
  "Lorem ipsum dolor sit amet consectetur adipisicing elit. Est minima labore quisquam nulla dolores pariatur provident, nemo, fuga id quae iusto consequuntur! Voluptate excepturi labore quisquam, officia quos sunt eveniet mollitia amet et! Numquam minima, animi aliquam cum nam deleniti!",
  " Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nostrum ad illum neque vero eum itaque tempore quod ullam, voluptatibus at perspiciatis culpa ratione perferendis dolores animi ea corrupti optio consequatur quia, rem hic placeat nam. Voluptates sunt veniam illum aperiam, similique eaque quod quo. Praesentium!",
  " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Natus quo cupiditate assumenda, inventore vitae reprehenderit, dolor odio sit iure similique officiis fuga repellat nam tempora possimus sequi maiores. In recusandae quis enim magni veniam voluptatum vitae repellendus nostrum placeat aliquid culpa mollitia repudiandae, optio rem!",
  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores cupiditate reprehenderit dignissimos numquam blanditiis mollitia tempora hic reiciendis. Et, aliquam! Quaerat esse ipsam minus molestias reiciendis expedita voluptas labore earum, possimus doloremque. Atque necessitatibus quaerat provident repellendus laudantium architecto, ut doloremque consequuntur ducimus molestias voluptates.",
  " Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis quod eius libero! Odio vero id aliquid, esse necessitatibus nam provident, earum minima sint deleniti rerum dolores, voluptatem ducimus in quibusdam. Eveniet at autem eligendi quis beatae cum, iste similique, ex ea dolore ratione possimus repellat.",
  " Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae sequi voluptas suscipit rerum vel cupiditate, eos repellendus nobis non vitae ipsum aliquid neque delectus temporibus ducimus modi aut libero eaque. Sint dolor fugiat accusantium sunt ducimus, distinctio error similique, itaque rem, laboriosam quidem ex minima.",
  "  Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas pariatur similique esse asperiores soluta maiores dolorem optio itaque fugiat. Praesentium, excepturi eligendi culpa eius quae quas velit iste animi rerum aperiam, tempora nam iusto soluta similique eaque. Veritatis nisi recusandae illo sit veniam, ratione blanditiis.",
];

export default Data;
